language: ruby
dist: precise
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - 2.1.10
install:
  - bundle install
  - gem build is_master.gemspec
  - gem install is_master-$(cat VERSION).gem
script:
  - rubocop
  - ruby ./test/test_cli_master.rb
  - ruby ./test/test_cli_slave.rb
